const popularMoviesConst = [
  {
    "Title": "Joker",
    "Year": "2019",
    "Rated": "R",
    "Released": "04 Oct 2019",
    "Runtime": "122 min",
    "Genre": "Crime, Drama, Thriller",
    "Director": "Todd Phillips",
    "Writer":
        "Todd Phillips, Scott Silver, Bob Kane (based on characters created by), Bill Finger (based on characters created by), Jerry Robinson (based on characters created by)",
    "Actors": "Joaquin Phoenix, Robert De Niro, Zazie Beetz, Frances Conroy",
    "Plot":
        "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.",
    "Language": "English",
    "Country": "USA, Canada",
    "Awards": "Won 2 Oscars. Another 57 wins & 163 nominations.",
    "Poster":
        "https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "Ratings": "68%",
    "Metascore": "59",
    "imdbRating": "8.6",
    "imdbVotes": "665,555",
    "imdbID": "tt7286456",
    "Type": "movie",
    "DVD": "17 Dec 2019",
    "BoxOffice": "N/A",
    "Production": "Warner Bros. Pictures",
    "Website": "N/A",
    "Response": "True",
  },
  {
    "Title": "Harry Potter and the Deathly Hallows: Part 2",
    "Year": "2011",
    "Rated": "PG-13",
    "Released": "15 Jul 2011",
    "Runtime": "130 min",
    "Genre": "Adventure, Drama, Fantasy, Mystery",
    "Director": "David Yates",
    "Writer": "Steve Kloves (screenplay), J.K. Rowling (novel)",
    "Actors": "Ralph Fiennes, Michael Gambon, Alan Rickman, Daniel Radcliffe",
    "Plot":
        "Harry, Ron, and Hermione search for Voldemort's remaining Horcruxes in their effort to destroy the Dark Lord as the final battle rages on at Hogwarts.",
    "Language": "English",
    "Country": "UK, USA",
    "Awards": "Nominated for 3 Oscars. Another 45 wins & 91 nominations.",
    "Poster":
        "https://m.media-amazon.com/images/M/MV5BMjIyZGU4YzUtNDkzYi00ZDRhLTljYzctYTMxMDQ4M2E0Y2YxXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg",
    "Ratings": '96%',
    "Metascore": "87",
    "imdbRating": "8.1",
    "imdbVotes": "718,729",
    "imdbID": "tt1201607",
    "Type": "movie",
    "DVD": "11 Nov 2011",
    "BoxOffice": "\$381,000,185",
    "Production": "Warner Bros. Pictures",
    "Website": "N/A",
    "Response": "True"
  },
  {
    "Title": "Avengers: Infinity War",
    "Year": "2018",
    "Rated": "PG-13",
    "Released": "27 Apr 2018",
    "Runtime": "149 min",
    "Genre": "Action, Adventure, Sci-Fi",
    "Director": "Anthony Russo, Joe Russo",
    "Writer":
        "Christopher Markus (screenplay by), Stephen McFeely (screenplay by), Stan Lee (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by), Joe Simon (Captain America created by), Jack Kirby (Captain America created by), Steve Englehart (Star-Lord created by), Steve Gan (Star-Lord created by), Bill Mantlo (Rocket Raccoon created by), Keith Giffen (Rocket Raccoon created by), Jim Starlin (Thanos, Gamora and Drax created by), Stan Lee (Groot created by), Larry Lieber (Groot created by), Jack Kirby (Groot created by), Steve Englehart (Mantis created by), Don Heck (Mantis created by)",
    "Actors": "Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans",
    "Plot":
        "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
    "Language": "English",
    "Country": "USA",
    "Awards": "Nominated for 1 Oscar. Another 44 wins & 70 nominations.",
    "Poster":
        "https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg",
    "Ratings": '85%',
    "Metascore": "68",
    "imdbRating": "8.5",
    "imdbVotes": "748,996",
    "imdbID": "tt4154756",
    "Type": "movie",
    "DVD": "14 Aug 2018",
    "BoxOffice": "\$664,987,816",
    "Production": "Walt Disney Pictures",
    "Website": "N/A",
    "Response": "True"
  },
  {
    "Title": "Dragon Ball Super: Broly",
    "Year": "2018",
    "Rated": "PG",
    "Released": "16 Jan 2019",
    "Runtime": "100 min",
    "Genre": "Animation, Action, Adventure, Family, Fantasy, Sci-Fi",
    "Director": "Tatsuya Nagamine",
    "Writer": "Akira Toriyama (character creator), Akira Toriyama (screenplay)",
    "Actors": "Masako Nozawa, Aya Hisakawa, Ryô Horikawa, Toshio Furukawa",
    "Plot":
        "Goku and Vegeta encounter Broly, a Saiyan warrior unlike any fighter they've faced before.",
    "Language": "Japanese",
    "Country": "Japan",
    "Awards": "1 nomination.",
    "Poster":
        "https://m.media-amazon.com/images/M/MV5BMjhhMDU5Y2QtMzcyZS00ZGE1LTg3ZjMtMTYyOTM0OTFlYTRkXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    "Ratings": '96%',
    "Metascore": "59",
    "imdbRating": "7.9",
    "imdbVotes": "19,714",
    "imdbID": "tt7961060",
    "Type": "movie",
    "DVD": "N/A",
    "BoxOffice": "N/A",
    "Production": "N/A",
    "Website": "N/A",
    "Response": "True"
  }
];
